# Generated by Django 4.2.5 on 2023-09-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memories',
            options={'verbose_name': 'Памятное место', 'verbose_name_plural': 'Памятные места'},
        ),
        migrations.RemoveField(
            model_name='memories',
            name='place_city',
        ),
        migrations.RemoveField(
            model_name='memories',
            name='place_country',
        ),
        migrations.AddField(
            model_name='memories',
            name='place_city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='memories',
            name='place_country',
            field=models.CharField(default='', max_length=250),
        ),
    ]
