# Generated by Django 4.2.5 on 2023-09-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0002_alter_memories_options_remove_memories_place_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='place_city',
            field=models.CharField(choices=[('Нюрнберг', 'Нюрнберг'), ('Штутгарт', 'Штутгарт')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='memories',
            name='place_country',
            field=models.CharField(choices=[('Германия', 'Германия')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='memories',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
