# Generated by Django 4.2.5 on 2023-09-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_alter_memories_place_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(blank=True, default='default.img', null=True, upload_to='memories/pics')),
                ('image_url', models.URLField(blank=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mem_image', to='memories.memories')),
            ],
        ),
    ]
