# Generated by Django 4.2.5 on 2023-09-24 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memories', '0004_imagememory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagememory',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='imagememory',
            name='image_data',
            field=models.ImageField(default='default.jpg', upload_to='memories/pics'),
        ),
        migrations.AlterField(
            model_name='imagememory',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='memories',
            name='place_city',
            field=models.CharField(choices=[('Нюрнберг', 'Нюрнберг'), ('Штутгарт', 'Штутгарт'), ('Берлин', 'Берлин')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='memories',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='memory_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
