# Generated by Django 4.2.5 on 2023-09-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_alter_imagememory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagememory',
            name='image_data',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='memories/pics'),
        ),
        migrations.AlterField(
            model_name='imagememory',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
