# Generated by Django 4.2.5 on 2023-09-26 09:53

from django.db import migrations, models
import memories.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_alter_imagememory_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='place_coord_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memories',
            name='place_coord_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imagememory',
            name='image_data',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=memories.models.get_memory_image_path),
        ),
    ]
