# Generated by Django 4.2.5 on 2023-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_memories_place_coord_lat_memories_place_coord_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='place_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
