# Generated by Django 4.2.5 on 2023-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0008_memories_place_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='place_city',
            field=models.CharField(blank=True, choices=[('Нюрнберг', 'Нюрнберг'), ('Штутгарт', 'Штутгарт'), ('Берлин', 'Берлин')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='memories',
            name='place_country',
            field=models.CharField(blank=True, choices=[('Германия', 'Германия')], max_length=250, null=True),
        ),
    ]
